### ISSUE TITLE
Update social media links

### ISSUE THREAD

**Issue by mattj65817** [Capitol-City-Flyers/capcityflyers.com#28]
* Per Corey's request, make the link to CCF Facebook more prominent on the page.
* Remove the YouTube link, or link it to a new account that is under our control.

**Comment by sudheesanamp2003** [comment]
i will take it

**Comment by TommieGunn** [comment]
Add Google Analytics to the website.
Copy and paste the below js to every page of the website, immediately after the <head> element. Or into the site template if the page head is generated by a template. Don’t add more than one Google tag to each page.


<script async src="https://www.googletagmanager.com/gtag/js?id=G-H9QC01BM3Z"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-H9QC01BM3Z');
</script>

**Comment by mattj65817** [comment]
Addressed in #42.
